{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-jackson",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pdedykfcdfc4jjcozzvjnyeega"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jackson-1.0.2.jar",
          "url": "hogcaller-jackson-1.0.2.jar",
          "size": 4810,
          "sha512": "60f8fead5990602c7c8b84d96ee25645678eb22096ba27775fe3a4ac342c634aa8d02e7b86ee1fb34e644753152270bd23796430d837d0f75ef64eec5b75b8cb",
          "sha256": "5b6fa11b0526536ba996180921fa22b3dd246fc7a09678d27d138dd440a08cfb",
          "sha1": "1282f5ac48443435c4b5d1d7c7b6d91e8945fba4",
          "md5": "c7e7f71991bfd7e55a65a7be518dbbec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jackson-1.0.2.jar",
          "url": "hogcaller-jackson-1.0.2.jar",
          "size": 4810,
          "sha512": "60f8fead5990602c7c8b84d96ee25645678eb22096ba27775fe3a4ac342c634aa8d02e7b86ee1fb34e644753152270bd23796430d837d0f75ef64eec5b75b8cb",
          "sha256": "5b6fa11b0526536ba996180921fa22b3dd246fc7a09678d27d138dd440a08cfb",
          "sha1": "1282f5ac48443435c4b5d1d7c7b6d91e8945fba4",
          "md5": "c7e7f71991bfd7e55a65a7be518dbbec"
        }
      ]
    }
  ]
}
