{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-mybatis",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qfxofga3vfbz3mlh2abimduvme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-mybatis-1.0.1.jar",
          "url": "hogcaller-mybatis-1.0.1.jar",
          "size": 10200,
          "sha512": "69e299149706f369d905690aa64366151bb343ff86a228ac0dae64b6cf2c2f7a59d9337e8685fd7fb1a7090a2c8a0fd77b705fa177da1e01f674332a1e58726e",
          "sha256": "609a89760f9ccaf7e920aa0683a3a3c5475fceefafe81a80e1d63ed6e148dff3",
          "sha1": "702d209e6e3e5d1908b48632ab479c60d34841ca",
          "md5": "9e8dccaa66b6891c9b1646c3fa08d725"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.baomidou",
          "module": "mybatis-plus",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-mybatis-1.0.1.jar",
          "url": "hogcaller-mybatis-1.0.1.jar",
          "size": 10200,
          "sha512": "69e299149706f369d905690aa64366151bb343ff86a228ac0dae64b6cf2c2f7a59d9337e8685fd7fb1a7090a2c8a0fd77b705fa177da1e01f674332a1e58726e",
          "sha256": "609a89760f9ccaf7e920aa0683a3a3c5475fceefafe81a80e1d63ed6e148dff3",
          "sha1": "702d209e6e3e5d1908b48632ab479c60d34841ca",
          "md5": "9e8dccaa66b6891c9b1646c3fa08d725"
        }
      ]
    }
  ]
}
