{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-jwt",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qfxofga3vfbz3mlh2abimduvme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jwt-1.0.1.jar",
          "url": "hogcaller-jwt-1.0.1.jar",
          "size": 3559,
          "sha512": "59ba1c9161dde7f0df1f929159e71939491f4c0f277d011f58d9124261eb0f585dd205d23d2688a174bcd80fe355e9e8f871573fcdcc374375ddf8c05f8cc209",
          "sha256": "92abced632aa247dfc040f3b7c4a2c862a52c177c00e7ae07968efcf0da88be6",
          "sha1": "0188b569f4b63eb7b2bc3cbd6f794f191c8e266b",
          "md5": "a02fd2bf597158696c21f36224f57781"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jwt-1.0.1.jar",
          "url": "hogcaller-jwt-1.0.1.jar",
          "size": 3559,
          "sha512": "59ba1c9161dde7f0df1f929159e71939491f4c0f277d011f58d9124261eb0f585dd205d23d2688a174bcd80fe355e9e8f871573fcdcc374375ddf8c05f8cc209",
          "sha256": "92abced632aa247dfc040f3b7c4a2c862a52c177c00e7ae07968efcf0da88be6",
          "sha1": "0188b569f4b63eb7b2bc3cbd6f794f191c8e266b",
          "md5": "a02fd2bf597158696c21f36224f57781"
        }
      ]
    }
  ]
}
