{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-observer-annotations",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "pdedykfcdfc4jjcozzvjnyeega"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-observer-annotations-1.0.2.jar",
          "url": "hogcaller-observer-annotations-1.0.2.jar",
          "size": 3956,
          "sha512": "7ce50b680b760790ff281fd9373f176b9b48ecf39397590f086e278570ac16e91e7caaf3a4283eb07561c95c7cdcfa491150158fcb9a11a8cc1173ee55ba2da9",
          "sha256": "c751b632370b5d3b40330d56f688971e37e42ce3af701ff7e65bfaaa6bf508bf",
          "sha1": "4236f2858a5d3dec77493e50e65e65175834381b",
          "md5": "5354a08269ccd7137ece89bf2438ebf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-observer-annotations-1.0.2.jar",
          "url": "hogcaller-observer-annotations-1.0.2.jar",
          "size": 3956,
          "sha512": "7ce50b680b760790ff281fd9373f176b9b48ecf39397590f086e278570ac16e91e7caaf3a4283eb07561c95c7cdcfa491150158fcb9a11a8cc1173ee55ba2da9",
          "sha256": "c751b632370b5d3b40330d56f688971e37e42ce3af701ff7e65bfaaa6bf508bf",
          "sha1": "4236f2858a5d3dec77493e50e65e65175834381b",
          "md5": "5354a08269ccd7137ece89bf2438ebf0"
        }
      ]
    }
  ]
}
