{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-observer-annotations",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jzvd5jge2rg5hly34g5shup46e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-observer-annotations-1.0.2.jar",
          "url": "hogcaller-observer-annotations-1.0.2.jar",
          "size": 3840,
          "sha512": "0ae593b4c7ebc5aed04f352005d39cb068632af650fc73d9ea07ac3b31d9e64afb0ebfcd53d44b7b05272023e66c468ab75b79bd189d80cb6a21efa69ac435c6",
          "sha256": "cad18d1fa00c7166b84b84edc1c88b48a0c505ae59886fe8e941ba568e29d6e5",
          "sha1": "518bfb1a2d42c56244b3932ff5d56560013d4c25",
          "md5": "decad975de9c07fa7d21b300a8480f8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-observer-annotations-1.0.2.jar",
          "url": "hogcaller-observer-annotations-1.0.2.jar",
          "size": 3840,
          "sha512": "0ae593b4c7ebc5aed04f352005d39cb068632af650fc73d9ea07ac3b31d9e64afb0ebfcd53d44b7b05272023e66c468ab75b79bd189d80cb6a21efa69ac435c6",
          "sha256": "cad18d1fa00c7166b84b84edc1c88b48a0c505ae59886fe8e941ba568e29d6e5",
          "sha1": "518bfb1a2d42c56244b3932ff5d56560013d4c25",
          "md5": "decad975de9c07fa7d21b300a8480f8e"
        }
      ]
    }
  ]
}
