{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-base",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qfxofga3vfbz3mlh2abimduvme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-base-1.0.1.jar",
          "url": "hogcaller-base-1.0.1.jar",
          "size": 37210,
          "sha512": "434034f35537807f4df2d8517d5a40349d30866f60c278b8800fc318ba1d4d42257018626c0e2753247dd53ed6bc8835bd2a6ba4c5a7c7cad392b1365f27ea07",
          "sha256": "0574fffe8e9f15162cca41e5fda493aaec60aae2148892ddc9c94885e9e7c4b8",
          "sha1": "88ce68e74409c0bbe7f8b6f2a1b5fe342f07acfa",
          "md5": "e0b615e020ecf8efb05e7155c76f600d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-base-1.0.1.jar",
          "url": "hogcaller-base-1.0.1.jar",
          "size": 37210,
          "sha512": "434034f35537807f4df2d8517d5a40349d30866f60c278b8800fc318ba1d4d42257018626c0e2753247dd53ed6bc8835bd2a6ba4c5a7c7cad392b1365f27ea07",
          "sha256": "0574fffe8e9f15162cca41e5fda493aaec60aae2148892ddc9c94885e9e7c4b8",
          "sha1": "88ce68e74409c0bbe7f8b6f2a1b5fe342f07acfa",
          "md5": "e0b615e020ecf8efb05e7155c76f600d"
        }
      ]
    }
  ]
}
