{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-jackson",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qfxofga3vfbz3mlh2abimduvme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jackson-1.0.1.jar",
          "url": "hogcaller-jackson-1.0.1.jar",
          "size": 4810,
          "sha512": "abfed218c781484e31abadcd20569f33cfa07f0b340dfde8c3cf58b690b3b996ce8356c236b8679369971266df96490f91d51467cc1945fbe6fd6d374f170c9b",
          "sha256": "dcc0e3a5e258a76f0f2139ce59d5d83c5f6725fcb27c81c741b45fe9f88c4d98",
          "sha1": "c4a0cbcf299d41179df62042c8124b33bd8444d2",
          "md5": "6dfa41d7124c945320e0ba9c000e6d15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.11.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.11.3"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-jackson-1.0.1.jar",
          "url": "hogcaller-jackson-1.0.1.jar",
          "size": 4810,
          "sha512": "abfed218c781484e31abadcd20569f33cfa07f0b340dfde8c3cf58b690b3b996ce8356c236b8679369971266df96490f91d51467cc1945fbe6fd6d374f170c9b",
          "sha256": "dcc0e3a5e258a76f0f2139ce59d5d83c5f6725fcb27c81c741b45fe9f88c4d98",
          "sha1": "c4a0cbcf299d41179df62042c8124b33bd8444d2",
          "md5": "6dfa41d7124c945320e0ba9c000e6d15"
        }
      ]
    }
  ]
}
