{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-spring",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qfxofga3vfbz3mlh2abimduvme"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-spring-1.0.1.jar",
          "url": "hogcaller-spring-1.0.1.jar",
          "size": 6483,
          "sha512": "1e7d93c442c38e8f158b27f7db5d25ef1bbce69c97a376ea8381c05dd5cfc5b757c01df4cf97bff937018d9439ec53a66596c636751042f91dfd62da9f530d01",
          "sha256": "4cc2e7bd8e6aa8986b4b2265242d632c4b21444f97f1caa6aa6436f707d30faa",
          "sha1": "de372ef1bfd3aa854485905046ccce8668afedb2",
          "md5": "e3dabf70ba556263d37c9a217b7fac9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.bytengine.own.hogcaller",
          "module": "hogcaller-base",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-spring-1.0.1.jar",
          "url": "hogcaller-spring-1.0.1.jar",
          "size": 6483,
          "sha512": "1e7d93c442c38e8f158b27f7db5d25ef1bbce69c97a376ea8381c05dd5cfc5b757c01df4cf97bff937018d9439ec53a66596c636751042f91dfd62da9f530d01",
          "sha256": "4cc2e7bd8e6aa8986b4b2265242d632c4b21444f97f1caa6aa6436f707d30faa",
          "sha1": "de372ef1bfd3aa854485905046ccce8668afedb2",
          "md5": "e3dabf70ba556263d37c9a217b7fac9c"
        }
      ]
    }
  ]
}
