{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.bytengine.own.hogcaller",
    "module": "hogcaller-base",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jzvd5jge2rg5hly34g5shup46e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-base-1.0.2.jar",
          "url": "hogcaller-base-1.0.2.jar",
          "size": 37210,
          "sha512": "b5bdb43701afda72ba65e35cd1ed2e72279c041776b657865b14cac4b4928282c2c145911254f1d323c2838e837bcbe553492473ab421fbb5ad4094bea96a200",
          "sha256": "b4ba16d11ff550c7fb01618f2870beb355e3cf3668c983d8ad820d42a61cbcff",
          "sha1": "48516388f67edbf0db098b0f60f71d07b2f96503",
          "md5": "25884938022c78f1ad5b627ea5c6f7d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.11"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.0-jre"
          }
        }
      ],
      "files": [
        {
          "name": "hogcaller-base-1.0.2.jar",
          "url": "hogcaller-base-1.0.2.jar",
          "size": 37210,
          "sha512": "b5bdb43701afda72ba65e35cd1ed2e72279c041776b657865b14cac4b4928282c2c145911254f1d323c2838e837bcbe553492473ab421fbb5ad4094bea96a200",
          "sha256": "b4ba16d11ff550c7fb01618f2870beb355e3cf3668c983d8ad820d42a61cbcff",
          "sha1": "48516388f67edbf0db098b0f60f71d07b2f96503",
          "md5": "25884938022c78f1ad5b627ea5c6f7d2"
        }
      ]
    }
  ]
}
